### ISSUE TITLE
Event type "networkError" not fired when ImageUrlSource does not exist

### ISSUE THREAD

**Issue by Schoude** [google/marzipano#264]
The "networkError" event type is not fired since version 0.9.0 for non existing image urls.

The following javascript error is thrown before the event can be fired.

```
ImageUrl.js?387e:100 Uncaught TypeError: now is not a function
    at eval (ImageUrl.js?387e:100)
    at WorkQueue._finish (WorkQueue.js?948e:106)
    at onced (once.js?fc80:24)
    at Image.img.onerror (HtmlImage.js?3a32:102)
```

The call to `now()` throws before emit can be triggered.

```js
if (err instanceof NetworkError) {
  // If a network error occurred, wait before retrying.
  retryMap[url] = now();
  self.emit('networkError', asset, err);
}
done(err, tile);
```

This was working in version 0.8.0.

**Comment by tjgq** [comment]
This was fixed in master (8653e25) but it hasn't been released yet.

I will do a point release later this week.

**Comment by b-strauss** [comment]
When can we expect this to be fixed?

**Comment by tjgq** [comment]
Sorry for the delay - just published 0.9.1.
